CREATE TABLE IF NOT EXISTS mbhlmaintenance.inspection_completions (
  completion_id               SERIAL PRIMARY KEY,
  inspection_id               INT NOT NULL REFERENCES mbhlmaintenance.inspections,
  work_order_id               INT NOT NULL,
  signed_by                   INT NOT NULL REFERENCES mbhlcore.personnel,
  signed_date                 DATE NOT NULL,
  airtime_at_completion       NUMERIC,
  cycles_at_completion        INT,
  date_at_completion          DATE NOT NULL,
  hobbs_at_completion         NUMERIC,
  cert_date                   DATE,
  airtime_at_due              NUMERIC,
  cycles_at_due               INT,
  date_at_due                 DATE,
  hobbs_at_due                NUMERIC,
  is_in_progress              BOOLEAN NOT NULL DEFAULT FALSE,
  in_progress_started_airtime NUMERIC,
  in_progress_started_date    DATE,
  in_progress_note            TEXT,
  requires_dual_inspection    BOOLEAN NOT NULL DEFAULT FALSE,
  dual_signed_by              INT REFERENCES mbhlcore.personnel,
  dual_signed_date            DATE,
  requires_flight_test        BOOLEAN NOT NULL DEFAULT FALSE,
  flight_test_satisfied_date  DATE,
  is_voided                   BOOLEAN NOT NULL DEFAULT FALSE,
  voided_reason               TEXT,
  voided_by                   INT REFERENCES mbhlcore.personnel,
  voided_date                 DATE,
  superseded_by_completion_id INT REFERENCES mbhlmaintenance.inspection_completions
);
