CREATE TABLE IF NOT EXISTS mbhlmaintenance.deferrals (
  deferral_id            SERIAL PRIMARY KEY,
  aircraft_id            INT NOT NULL REFERENCES mbhlcore.aircraft,
  origin_type            TEXT NOT NULL CHECK (origin_type IN ('wo_task', 'manual_entry')),
  snag_task_id           INT REFERENCES mbhlmaintenance.wo_tasks,
  defect_description     TEXT NOT NULL,
  deferred_system        TEXT NOT NULL,
  deferral_type          TEXT NOT NULL CHECK (deferral_type IN ('mel', 'non_mel')),
  mel_item_ref           TEXT,
  mel_o_action_required  BOOLEAN NOT NULL DEFAULT FALSE,
  mel_m_action_type      TEXT CHECK (mel_m_action_type IN ('M', 'M#')),
  mel_m_signed_by        INT REFERENCES mbhlcore.personnel,
  mel_m_signed_date      DATE,
  regulatory_refs        TEXT,
  manufacturer_refs      TEXT,
  due_date               DATE,
  due_airtime            NUMERIC,
  is_active              BOOLEAN NOT NULL DEFAULT TRUE,
  closed_by_wo_id        INT REFERENCES mbhlmaintenance.work_orders,
  closed_date            DATE,
  entered_by             INT NOT NULL REFERENCES mbhlcore.personnel,
  entered_date           DATE NOT NULL,
  notes                  TEXT
);
